modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="arvigoswordmod" #mandatory
version="1.1" #mandatory
displayName="Arvigo's Sword Mod" #mandatory
logoFile="swordItem.png" #optional
credits="Your Mother" #optional
authors="Arvigo" #optional
description='''
Arvigo's Lovely Mod

'''

# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
